### ISSUE TITLE
Is there any plan to support acpi-cpufreq driver for pstates?

### ISSUE THREAD

**Issue by chengfen1987** [intel/power-optimization-library#4]
Current, pstate support intel_pstate, intel_cpufreq driver. And cstate support intel_idle, acpi_idle driver. Does anyone know that the plan support acpi-cpufreq driver for pstates?

**Comment by catblade** [comment]
We will expand to that this year, but not sure on which dates yet.  Would you like us to keep this issue open and comment when the work is pushed?

**Comment by catblade** [comment]
Also, the acpi-cpufreq driver has many modes.  Are there particular ones you would prioritize?

**Comment by chengfen1987** [comment]
What is the mode of acpi-cpufreq driver? If it is the governor value (eg. conservative ondemand userspace powersave performance) in /sys/devices/system/cpu/cpuX/cpufreq/scaling_governor. We want to use "userspace" governor in our dpdk process.

**Comment by patricia-cahill** [comment]
Hey we are just about to release the Power Optimization Library v1.3.0 this week that has ACPI driver functionality enabled
